# Generated by Django 4.2.4 on 2023-09-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_dept', '0002_remove_hruser_test_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hruser',
            table='HRUser',
        ),
    ]
