# Generated by Django 5.0 on 2023-12-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercar',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
