# Generated by Django 5.0.1 on 2024-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_cardailyreports_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardailyreports',
            name='car_mileage',
            field=models.CharField(max_length=7),
        ),
    ]
