# Generated by Django 4.2.4 on 2023-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_drivercar'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercar',
            name='additional_remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drivercar',
            name='car_cleanliness',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=5),
        ),
        migrations.AddField(
            model_name='drivercar',
            name='car_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='drivercar',
            name='car_mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='drivercar',
            table='DD_report',
        ),
    ]
