# Generated by Django 5.0.1 on 2024-01-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_cardailyreports_car_mileage'),
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car_mileage', models.CharField(max_length=7)),
                ('description', models.TextField(max_length=1000)),
                ('car', models.ForeignKey(db_column='car', on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('driver', models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
