# Generated by Django 5.0.1 on 2024-01-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_cardamage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardamage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
