# Generated by Django 5.0.1 on 2024-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_car_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone_policy_contact',
            field=models.CharField(max_length=20),
        ),
    ]
