# Generated by Django 5.0 on 2023-12-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cars', models.ManyToManyField(blank=True, db_column='cars', to='car.car')),
            ],
        ),
    ]
