# Generated by Django 4.2.7 on 2023-11-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cars', models.ManyToManyField(blank=True, to='car.car')),
            ],
        ),
    ]
