# Generated by Django 4.2.4 on 2023-09-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetuser',
            name='test_field',
        ),
    ]
