# Generated by Django 4.2.4 on 2023-09-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_dept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolluser',
            name='test_field',
        ),
    ]
