# Generated by Django 4.2.4 on 2023-08-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_remove_driver_avalible_restaurants'),
        ('car', '0003_drivercar_additional_remarks_and_more'),
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='WorkChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(max_length=5)),
                ('time_end', models.CharField(max_length=5)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('daily_cars_schedules', models.ManyToManyField(blank=True, to='restaurant.dailycarschedule')),
            ],
        ),
        migrations.AddField(
            model_name='dailycarschedule',
            name='work_changes',
            field=models.ManyToManyField(blank=True, to='restaurant.workchange'),
        ),
    ]
