# Generated by Django 5.0.1 on 2024-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='driver.driver'),
        ),
    ]
