# Generated by Django 5.0.1 on 2024-02-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_phone_policy_contact'),
        ('restaurant', '0002_alter_brands_phone_alter_restaurant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycarschedule',
            name='car',
            field=models.ForeignKey(db_column='car', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='brand',
            field=models.ForeignKey(db_column='brand', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.brands'),
        ),
    ]
