# Generated by Django 4.2.4 on 2023-09-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dailycarschedule_workchange_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip_code',
        ),
    ]
