# Generated by Django 4.2.4 on 2023-08-29 18:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restmanager',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='restmanager',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='restmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='restmanager',
            name='username',
        ),
        migrations.AddField(
            model_name='restmanager',
            name='generaluser_ptr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
