# Generated by Django 4.2.4 on 2023-09-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restmanager',
            name='test_field',
        ),
    ]
