# Generated by Django 4.2.4 on 2023-09-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='user_role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('HR', 'HR'), ('Payroll', 'Payroll'), ('Asset', 'Asset'), ('Clients', 'Clients'), ('Manager', 'Manager'), ('Driver', 'Driver'), ('Administrator', 'Administrator')], default='Administrator', max_length=20),
        ),
    ]
