# Generated by Django 4.2.4 on 2023-08-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='user_rank',
            new_name='user_role',
        ),
    ]
