# Generated by Django 4.2.4 on 2023-09-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_generaluser_city_generaluser_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='street_address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='generaluser',
            name='apartament_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='home_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
