# Generated by Django 4.2.4 on 2023-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_generaluser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='nfz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='pesel_nip',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_apartament_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_home_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
