# Generated by Django 4.2.4 on 2023-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_generaluser_bank_account_number_generaluser_nfz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='apartament_number',
            new_name='correspondence_apartament_number',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='city',
            new_name='correspondence_city',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='country',
            new_name='correspondence_country',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='home_number',
            new_name='correspondence_home_number',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='state',
            new_name='correspondence_state',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='street',
            new_name='correspondence_street',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='zip_code',
            new_name='correspondence_zip_code',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_apartament_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_home_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='registered_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_apartament_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_home_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='residence_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
