# Generated by Django 4.2.4 on 2023-09-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_apartament_number_generaluser_correspondence_apartament_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_apartament_number',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_city',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_country',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_home_number',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_state',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_street',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='tax_office_zip_code',
        ),
        migrations.AddField(
            model_name='generaluser',
            name='tax_office_address',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
