# Generated by Django 4.2.4 on 2023-09-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_generaluser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='pesel_nip',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='tax_office_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
