# Generated by Django 4.2.4 on 2023-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_work', models.TimeField()),
                ('end_work', models.TimeField()),
                ('orders', models.IntegerField(default=0)),
                ('working_time', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
