# Generated by Django 4.2.4 on 2023-08-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
        ('driver', '0002_dailywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='avalible_restaurants',
            field=models.ManyToManyField(to='restaurant.restaurant'),
        ),
    ]
