# Generated by Django 5.0 on 2023-12-22 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_username',
            field=models.CharField(default='empty', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='generaluser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('driver_username',)},
        ),
    ]
