# Generated by Django 5.0.1 on 2024-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_dailywork_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywork',
            old_name='day',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='working_time',
            field=models.TimeField(),
        ),
    ]
