# Generated by Django 5.0.1 on 2024-01-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_rename_day_dailywork_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailywork',
            table='DailyWorkReports',
        ),
    ]
