# Generated by Django 4.2.4 on 2023-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_remove_driver_avalible_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='phone_number123',
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
