# Generated by Django 5.0.1 on 2024-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_alter_dailywork_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='orders_per_hour',
            field=models.FloatField(default=0.0),
        ),
    ]
