# Generated by Django 4.2.4 on 2023-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driver_ln_code_driver_ln_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='ln_expire_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ln_release_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
