# Generated by Django 5.0.1 on 2024-02-08 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_dailywork_orders_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic_hourly_rate', models.FloatField()),
                ('orders_bonus', models.FloatField()),
                ('fuel_bonus', models.FloatField()),
            ],
            options={
                'db_table': 'WageTariff',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='wage_tariff',
            field=models.ForeignKey(blank=True, db_column='wage_tariff', null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.wagetariff'),
        ),
    ]
