# Generated by Django 5.0.1 on 2024-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_alter_driver_wage_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagetariff',
            name='starting_new_billing_period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
